services:
  - type: web
    name: flow2b
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 